### ISSUE TITLE
Unable to transmit packets in monitor mode

### ISSUE THREAD

**Issue by imzyxwvu** [ulli-kroll/mt7610u#30]
I used the following commands to switch the adapter to monitor:

    ifconfig wlan1 up
    iwconfig wlan1 mode monitor

iwconfig shows:
```
wlan1     Ralink STA  ESSID:""  Nickname:""
          Mode:Monitor  Frequency=2.412 GHz  Access Point: Not-Associated   
          Bit Rate:1 Mb/s   
          RTS thr:off   Fragment thr:off
          Encryption key:off
          Link Quality=10/100  Signal level:0 dBm  Noise level:0 dBm
          Rx invalid nwid:0  Rx invalid crypt:0  Rx invalid frag:0
          Tx excessive retries:0  Invalid misc:0   Missed beacon:0
```

airodump-ng could receive packets perfectly, but neither aireplay-ng nor airbase-ng could transmit packets. aireplay-ng --test shows probes were transmitted but no reply was received. The AP airbase-ng created is impossible to be found on other devices.

**Comment by ulli-kroll** [comment]
Sending packets in monitor mode is not supported by the vendor driver.
And I don't add this, because this is part of the old wireless-ext/cfg80211 interface.

The relevant code path is in
`os/linux/rt_profile.c`
lines 297-305

```
int RTMPSendPackets()
...
#ifdef CONFIG_STA_SUPPORT
	IF_DEV_CONFIG_OPMODE_ON_STA(pAd) {
		/* Drop send request since we are in monitor mode */
		if (MONITOR_ON(pAd)) {
			dev_kfree_skb_any(pPacket);
			return 0;
		}
	}
#endif /* CONFIG_STA_SUPPORT */
```

**Comment by imzyxwvu** [comment]
I need this, and I commented the check out. I also modified STASendPackets in sta/rtmp_data.c not to drop packets in monitor mode. But it does not send packets either. Does the device support sending packets in monitor mode?

**Comment by ulli-kroll** [comment]
This device (maybe ?) can send raw packets.
The problem here, which format is airplay-ng sending
prism or radiotap or raw ?
So this must be parsed.

Personally I don't care for this bug and won't fix them.
This is an cfg80211 issue which is not worth to fix, because of the timeframe to do this.
My main direction is mac80211

**Comment by imzyxwvu** [comment]
The format of packets aircrack-ng is sending is radiotap. Could you give me some hints so I could try to implement this feature?

**Comment by ulli-kroll** [comment]
> The format of packets aircrack-ng is sending is radiotap. Could you give me some hints so I could try to implement this feature?

radiotap format ??
IIRC the driver provide prism format, in monitor mode. I've discovered this while debugging the memory leak.

I don't implement this because this will go away with mac80211 support, so this is a waste of time.
Currently I'm wrapping my head around the mcu/mcu_and.c to remove all/most of the spinlocks.

For hint look into common/rtusb_bulk.c
RTUSBBulkOutDataPacket()
But this is may the "true"  function.
